### PR TITLE
Expose columnar to  execute_with_progress

### PR DESCRIPTION
**Pull request by igorbb**
Right now there is no way to set columnar  in execute_with_progress. It seems all it was missing was to expose the parameter.

### CODE REVIEW

**Comment by xzkostyan** [comment]
Great. Can you make a simple test to ensure this wouldn't break in the future? See this test case for example: https://github.com/mymarilyn/clickhouse-driver/blob/27edae4f8e1ec8526e2859fdc6336526eb3c59ee/tests/test_blocks.py

**Comment by igorbb** [comment]
@xzkostyan Added a test test_select_with_columar_with_column_types

**Comment by igorbb** [comment]
It seems the test is passing. https://travis-ci.org/mymarilyn/clickhouse-driver/jobs/589384652#L789
I don't know the some jobs is marked as fail.

**Comment by xzkostyan** [comment]
flake8 check fails: https://travis-ci.org/mymarilyn/clickhouse-driver/jobs/589384652#L546

**Pull request merged**
