### PR TITLE
Fix timeout for INSERT queries without params.

### PR DESCRIPTION
**Pull request by shotInLeg**
With use classic INSERT request execute method throw timeout exception, code showing this https://pastebin.com/V2kNpynf

### CODE REVIEW

**Comment by xzkostyan** [comment]
It's okay. There is no CTE clause in INSERT expression now.

Write test for this case to keep coverage at the same level.

**Comment by TheMcGoose** [comment]
This breaks valid queries that do an `insert into ... select from`... can this be reverted or fixed to allow that?  Example:

```
INSERT INTO test_v1
(
    val_1,
    val_2
)
SELECT
    val_1,
    val_2
FROM test_v2;
```
is a valid query but now fails with the error message:
`ValueError: For use INSERT queries set params argument`

**Comment by TheMcGoose** [comment]
This is also a functionality change, so it should not have been released as a patch number bump.

**Comment by xzkostyan** [comment]
I've suddenly missed this breaking change with `INSERT FROM SELECT`.

This was reverted in [0.0.13](https://pypi.org/project/clickhouse-driver/0.0.13/).

**Comment by TheMcGoose** [comment]
No problem, thanks for the quick fix @xzkostyan :)

**Pull request merged**
