### PR TITLE
add possibility to don't replace non-words by default

### PR DESCRIPTION
**Pull request by notsovitalik**
very symple addition to provide possibility to don't replace non-words characters in columns of data frame.
because currently it's provided by default, which is not very handy thing

### CODE REVIEW

**Comment by xzkostyan** [comment]
Good. Let's add simple test for it.

**Comment by notsovitalik** [comment]
test case added

**Comment by xzkostyan** [comment]
Okay. I'll fix flake8 errors.

**Comment by notsovitalik** [comment]
thanks!

**Pull request merged**
