### PR TITLE
ssl: add support for private key/certificate file

### PR DESCRIPTION
**Pull request by alexole**
Add support for keyfile/certfile for SSL connection

### CODE REVIEW

**Comment by xzkostyan** [comment]
LGTM. Please fix flake8: https://travis-ci.org/github/mymarilyn/clickhouse-driver/jobs/771795806 and PR will be merged

**Comment by alexole** [comment]
Fixed @xzkostyan

**Comment by alexole** [comment]
Should I do anything about coverage or not? Seems like a false positive.

**Comment by xzkostyan** [comment]
No, it's docker pull limit issue.

**Pull request merged**
