### PR TITLE
fix for pip install -e .

### PR DESCRIPTION
**Pull request by AchilleAsh**
Hi,
Similar to the issue in clickhouse-sqlalchemy ( https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/17 ) as it has the same setup.py, here's the fix to allow ```pip install -e .``` to work.

Thanks,
Timothé

### CODE REVIEW

**Comment by xzkostyan** [comment]
Hi!

Great, but tests are failed.

Btw, there is fix for issue in another branch: https://github.com/mymarilyn/clickhouse-driver/commit/14bef556bc366930bcb7eb8ba5b1dc7ce1dd57fd

**Comment by AchilleAsh** [comment]
Hi,

Oups sorry, I forget them... Do you have an ETA when you will merge the branch, or should I edit my PR and you will merge it with master before?

Note: You should replace find_packages('.') by ['clickhouse_driver'] in the setup.py because otherwise tests package gets also installed

**Comment by xzkostyan** [comment]
I'm planning to make release at the end of this week. You can edit your PR, but this is not necessary.

Thanks for pointing on tests issue.

**Comment by xzkostyan** [comment]
0.0.12 release with this fix has been published to PyPI.

**Pull request closed without merging**
