### PR TITLE
copy license into source dir for building wheel

### PR DESCRIPTION
**Pull request by revan57**

### CODE REVIEW

**Comment by xzkostyan** [comment]
Hi!

Can you provide some popular packages with license file included into sources in wheels?

psycopg2 alongside with lxml doesn't provide license file in sources of wheel package https://pypi.org/project/psycopg2-binary/ https://pypi.org/project/lxml/#files

Honestly I don't understand what's the problem with license in wheel packages.

**Comment by revan57** [comment]
My mistake, I've just founded that license is not provided in pypi package. It causes a failure when building a docker image.

**Comment by xzkostyan** [comment]
How can l reproduce this issue?

**Comment by revan57** [comment]
just try to build it

**Comment by xzkostyan** [comment]
My bad. License file was missed in version 0.1.0. I've just published version 0.1.1 with license included.

**Pull request closed without merging**
